Cte algorithm
sbc305/cognitive_practice pull request #23
Opened 2024-11-29 07:57 UTC by VariPor

2024-11-29 15:53 UTC, vicproon commented
а какой результат этих правок? стало ли по другому работать, например?

2024-11-29 15:53 UTC, vicproon requested changes, later dismissed

2024-11-29 15:53 UTC, vicproon commented on core/alg_modes.py
> +    if similarity > limit:
сейчас на вход подается корреляция. корреляция будет максимальна для одинаковых входов. раньше сравнивалось средняя отклонений. которая будет 0 для одинаковых входов.

кажется, надо, как минимум, делать `< limit`.

а еще в целом смысл в отдельной функции пропадает, проще написать где нужно `return corr < limit`, чем `return similarity_interpretation(corr, limit)`...

или вы хотели как бы сделать абстракцию, которую потом усложните? тогда как-то выразите это намерение, например в комментарии.

2024-11-29 15:53 UTC, vicproon commented on core/processing_algorithm.py
> +        return np.mean(np.max(correlate(self.etalon_modes[column], self.current_modes[column]), axis=0))
тут усреднение максимумов корреляции по всем модам? Лучше пояснить в комментарии

2024-11-29 16:40 UTC, VariPor commented on core/alg_modes.py
> +    if similarity > limit:
Мне тоже так кажется, но при запуске теста именно этот вариант '''< limit''' даёт более адекватный результат  
Возможно, дело в амплитудах? У нулевого проезда амплитуда достаточно маленькая по сравнению с остальными

2024-11-29 16:44 UTC, VariPor commented on core/alg_modes.py
> +    if similarity > limit:
Мне тоже так кажется, но при запуске теста именно этот вариант `> limit` даёт более адекватный результат.
Возможно, дело в амплитудах? У нулевого проезда амплитуда достаточно маленькая по сравнению с остальными.   
Да, я думаю, это надо усложнить, и, возможно, сделаю вывод по массиву, а не по сумме

2024-11-29 16:46 UTC, VariPor commented on core/processing_algorithm.py
> +        return np.mean(np.max(correlate(self.etalon_modes[column], self.current_modes[column]), axis=0))
Да, по всем модам, которые задал пользователь

2024-11-29 16:49 UTC, VariPor commented
Результат правок: код стал выглядеть проще и логичнее  
При этом некоторые проезды (4 и 6) очень похожи на эталонный (0), и различить их достаточно трудно и до внесения правок, и после, но возможно, дело в подборе параметров

2024-12-06 21:43 UTC, c4llery approved these changes

2024-12-06 21:46 UTC, merged